version: '2.1'

services:
    api-main:
      restart: always
      container_name: "api-main"
      image: alpine:3.10
      ports:
        - "3030:80"
      volumes:
        - "./:/tmp/api-main"
      command: "sh ./tmp/api-main/init.sh"
      privileged: true